server:
  port: 8082

spring:
  application:
    name: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka