server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: 'amigoscode'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka